server:
  port: 8081

spring:
  boot:
    admin:
      notify:
        mail:
          to: testReceiver@gmail.com
  security:
    user:
      name: adminId
      password: adminPw

  mail:
    host: smtp.gmail.com
    port: 587
    username: testSender@gmail.com
    password: fo4weigkugmbct1q
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true